# Generated by Django 5.0.7 on 2024-12-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelhub', '0002_rename_teammember_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='rating',
            new_name='ratings',
        ),
        migrations.AddField(
            model_name='booking',
            name='ratings',
            field=models.IntegerField(default=5),
        ),
    ]
